version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      PGUSER: mychatdev
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dbmychat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
